// <auto-generated />
using LogQuake.Infra.Data.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LogQuake.Infra.Migrations.SQLiteMigrations
{
    [DbContext(typeof(SQLiteLogQuakeContext))]
    partial class SQLiteLogQuakeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("LogQuake.Domain.Entities.Kill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("IdGame");

                    b.Property<string>("PlayerKilled")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("PlayerKiller")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.HasIndex("IdGame");

                    b.ToTable("Kill");
                });
#pragma warning restore 612, 618
        }
    }
}
